config/routes.rb
FatPenguin::Application.routes.draw do
  resources :facts
  root :to => "home#index"
  post "/message/:id"  => "home#message"
  resources :users, :only => [:index, :show, :edit, :update]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/models/fact.rb
class Fact < ActiveRecord::Base
  attr_accessible :content, :user_id
  validates :content, :user_id, :presence => true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :provider, :uid, :name, :email, :facts_attributes
  attr_accessible :latitude, :longitude, :altitude, :heading, :speed
  attr_accessible :acuracy, :altitudeAcuracy, :address, :peerjs_id
  
  reverse_geocoded_by :latitude, :longitude, :address => :address
  after_validation :reverse_geocode
  
  validates_presence_of :name
  has_many :facts
  accepts_nested_attributes_for :facts, reject_if: proc { |f| f['content'].blank? }, allow_destroy: true
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue Exception => e
      nil
    end
  end

  def user_signed_in?
    return true if current_user
  end

  def correct_user?
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url, :alert => "Access denied."
    end
  end

  def authenticate_user!
    if !current_user
      redirect_to root_url, :alert => 'You need to sign in for access to this page.'
    end
  end
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  def index
    @facts = Fact.all
  end

  def show
    @fact = Fact.find(params[:id])
  end
  
  def create
    @fact = Fact.new(params[:fact])
    if @fact.save
      render :show
    else
      render :json => @fact.errors.full_messages, :status => 422
    end
  end
  
  def update
    @fact = Fact.find(params[:id])
    if @fact.update_attributes(params[:fact])
      render :show
    else
      render :json => @fact.errors.full_messages, :status => 422
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
  
  def message
    Pusher['test_channel'].trigger('message', {
      message: params[:message],
      to_id: params[:id],
      from_id: params[:from_id]
    })
    render :json => nil
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
# Reset the session after successful login, per
# 2.8 Session Fixation – Countermeasures:
# http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    reset_session
    session[:user_id] = user.id
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = current_user.nearbys(30).to_a + [current_user]
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      render :show
    else
      render :edit
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
	<% if user_signed_in? %>
		FatPenguin.current_user_id = <%= current_user.id %>;
	<% end %>
	FatPenguin.token = "<%= form_authenticity_token %>";
  FatPenguin.initialize();
});
</script>

app/views/layouts/_edit.html.erb
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">I am.</h3>
  </div>
  <div class="modal-body">
    <label for="Name">Name</label>
		<input type="text" name="user[name]" value="" id="Name">
    <label for="Email">Email</label>
		<input type="email" name="user[email]" value="" id="Email"><br />
    <h4 id="myModalLabel">And I...</h4>
		<input type="text" name="" value="" id=""><br />
		<input type="text" name="" value="" id=""><br />
		<input type="text" name="" value="" id="">
		<button type="button" class="btn btn-small btn-success">+</button>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
    <button class="btn btn-primary" data-dismiss="modal">Go!</button>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<%= link_to "FatPenguin", root_path, :class => 'brand' %>
			<div class="nav-collapse collapse" id="main-menu">
				<ul class="nav" id="main-menu-left">
				  <% if user_signed_in? %>
				    <li>
							<a href="#myModal" role="button" data-toggle="modal">Me</a>
				    </li>
				    <li>
				    <%= link_to 'Logout', signout_path %>
				    </li>
				  <% else %>
				    <li>
				    <%= link_to 'Login', signin_path %>
				    </li>
				  <% end %>
				</ul>	
		</div>
	</div>
</div>

app/views/layouts/_splash.html.erb
<div class="splash text-center">
		<h1 class="logo black">FatPenguin</h1>
		<i>Breaking the ice since 2013.</i>
		<br />
			<%= link_to "<i class='icon-facebook'></i> | Connect with Facebook".html_safe, signin_path, :class => "btn btn-facebook" %>
</div>
<style type="text/css" media="screen">

body {
	background-image:url('<%= image_path 'wallpaper.jpg' %>');
	background-size: 100%;
	background-repeat: no-repeat;
}


@media screen and (max-width: 500px) {
	body {
		background-image:url('<%= image_path 'wallpaper-port.jpg' %>'); 
		padding-top: 60px; 
	}
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FatPenguin" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Fatpenguin" %>">
		<link href='http://fonts.googleapis.com/css?family=Chicle|Cantora+One|Emblema+One|Exo:400,900|Candal|Archivo+Black|Gorditas:400,700|Alegreya:400,900' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
		<script src="http://js.pusher.com/2.1/pusher.min.js" type="text/javascript"></script>
		
  <body>
		<% unless user_signed_in? %>
			<%= render :partial => 'layouts/splash' %>
		<% else %>
			<%= render 'layouts/navigation' %>
		
			<div id="notifications"></div>

	    <%= render 'layouts/messages' %>

			<div id="users-list">
	        <%= yield %>
			</div> 
		<% end %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.submit "Sign in" %>
<% end %>